### ISSUE TITLE
Link token pair selected when adding liquidity

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#104]
![image](https://user-images.githubusercontent.com/61826995/133018132-2c661fd9-703d-4424-a15d-18bb96b17748.png)
![image](https://user-images.githubusercontent.com/61826995/133018136-59a05cbc-548a-4327-bd77-7a0e35aa9ff6.png)

**Comment by mativanarquero** [comment]
Sir @swengr-janan, sang page po yang KCLP-BUSD Pair?

**Comment by swengr-janan** [comment]
Sa sparkswap.info @mativanarquero

**Comment by swengr-janan** [comment]
https://sparkswap.info/#/tokens

Lahat ng mga token pairs jan kapag mag add luquidity dapat matic naka select na si pair sa [Add Liquidity] page ni sparkswap 🎇
