### ISSUE TITLE
Update SparkSwap banners ( Add the following designs)

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#109]
![image](https://user-images.githubusercontent.com/61826995/160068514-cb1b9185-72d3-4346-8c9c-d5e2e4059c1c.png)

Designs:
![image](https://user-images.githubusercontent.com/61826995/160068578-1ef3ffa9-7f5f-4cb9-8dad-c664a53376e7.png)
![image](https://user-images.githubusercontent.com/61826995/160068587-2bb39602-43ba-42af-b672-d2df75b74909.png)
![image](https://user-images.githubusercontent.com/61826995/160068595-8da90592-4f7c-4897-ab51-f79d7509c305.png)
![image](https://user-images.githubusercontent.com/61826995/160068602-cf9742ca-daf9-4c8a-b609-37af8a0c9785.png)

**Comment by mativanarquero** [comment]
As in po to sir @swengr-janan, including the text "Explore our SparkSwap DApps"?

**Comment by swengr-janan** [comment]
Yes @mativanarquero
