### ISSUE TITLE
Change link to sparkswap website

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#126]
<img width="421" alt="Screen Shot 2022-05-23 at 10 32 16 AM" src="https://user-images.githubusercontent.com/61826995/169732448-097b800d-f0ee-4ed1-8696-716f4e358bd8.png">

**Comment by kojiadrianojr** [comment]
![image](https://user-images.githubusercontent.com/43143132/169732568-8a30bac0-44f0-4967-beea-ea231642ad86.png)

This will be resolved upon deploying the prod build
