### ISSUE TITLE
Language change not working

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#15]
![image](https://user-images.githubusercontent.com/61826995/110310243-48f04b80-803d-11eb-9772-619e72a429a7.png)

**Comment by kojiadrianojr** [comment]
Fix incoming pag na approve na ni master @aldrickb su pr ko.

**Comment by kojiadrianojr** [comment]
This is already an issue opened by @aldrickb kuya. Duplicate na po ito

**Comment by swengr-janan** [comment]
I see. Close ko na. Thanks @kojiadrianojr !
