### ISSUE TITLE
Supply links to the following buttons

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#154]
<img width="1286" alt="Screen Shot 2022-05-30 at 6 48 19 PM" src="https://user-images.githubusercontent.com/61826995/170977092-363c3ff2-15d9-4c7b-b349-b5c2fd23c957.png">

Get links here:
https://srk.finance/

**Comment by justinbalaguer** [comment]
ano link neto @swengr-janan ? website lang or diretso na kung ano nasa button?

**Comment by swengr-janan** [comment]
Yaon jan jazz sa website na tinao ko, may mga same button yan jan. Gamiton mo nalang su mga links na kapereho

**Comment by swengr-janan** [comment]
open mo yan na srk.finance tapos scroll down ka, yaon duman jazz

**Comment by justinbalaguer** [comment]
sa may sain duman ? pa turo daw di ko mahanap haha salamats

**Comment by swengr-janan** [comment]
![image](https://user-images.githubusercontent.com/61826995/170989219-ee382826-4dc2-447c-85a9-e53811eaed50.png)

ini jazz

**Comment by justinbalaguer** [comment]
thanksuu
