### ISSUE TITLE
tab scroll effects are not yet working

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#156]
<img width="566" alt="Screen Shot 2022-05-30 at 9 03 50 PM" src="https://user-images.githubusercontent.com/61826995/170998379-db9a349a-83c4-45c6-a779-f7e2841c9401.png">

**Comment by justinbalaguer** [comment]
working sako ini chokz. try mo daw dgdi if dae pa din saimo nagana https://sparkswap-dev.vercel.app/#/
