### ISSUE TITLE
PHP and USD value are the same

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#168]
<img width="465" alt="Screen Shot 2022-05-31 at 4 14 03 PM" src="https://user-images.githubusercontent.com/61826995/171125818-2d86a4c8-286e-422f-b65a-644b5c5f5432.png">

**Comment by justinbalaguer** [comment]
sigs sigs

**Comment by justinbalaguer** [comment]
su percentage tanggalon ko din muna? hardcoded din ito

**Comment by swengr-janan** [comment]
alion mo alang din jazz

**Comment by swengr-janan** [comment]
su powered by coingecko
<img width="466" alt="Screen Shot 2022-05-31 at 4 26 16 PM" src="https://user-images.githubusercontent.com/61826995/171128245-41ddc15e-105c-4b1e-ab1b-b41face00c15.png">

**Comment by justinbalaguer** [comment]
widget na kaso yan sa coingecko. try ko pa din hanapon sa api. or sa api ng coinmarketcap mismo. pero di ko muna sa ngunyan isabay, setup ko din kaya muna diretso sa api na gamit ko

**Comment by swengr-janan** [comment]
sige jazz, thank youu!
