### ISSUE TITLE
Night mode and Language button cannot be seen using Mobile Browser

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#17]
![image](https://user-images.githubusercontent.com/61826995/110316412-a9838680-8045-11eb-9233-7ddfdff182b1.png)

**Comment by kojiadrianojr** [comment]
Taken using dev tools on chrome: 
![image](https://user-images.githubusercontent.com/43143132/110570166-7699d980-8190-11eb-8e5e-0d552cdd4912.png)

Using browser on my mobile device: 
![image](https://user-images.githubusercontent.com/43143132/110570256-96c99880-8190-11eb-8835-b821ed55bbf3.png)

It's working on my end.

**Comment by swengr-janan** [comment]
Baka kasi sa phone ko lang di makita. Haha

**Comment by kojiadrianojr** [comment]
Baka dahil sa height po kuya @swengr-janan

**Comment by swengr-janan** [comment]
Wala rin problema sakin using dev tools on chrome. I tried it again using my mobile phone and still same, di makita. Siguro sa screen size ng phone ko.

**Comment by swengr-janan** [comment]
New UI. This is fixed!
