### ISSUE TITLE
Infinite loading spinner

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#18]
![image](https://user-images.githubusercontent.com/61826995/110436983-d3918300-80ef-11eb-92e1-c4363737db6a.png)

**Comment by kojiadrianojr** [comment]
Lumalabas to sa mainnet ng binance ano po? Wala pa po kasi tayong mainnet contract puros testnet palang. 

this is noted! :)

**Comment by swengr-janan** [comment]
I see. Kaya pala. Thank @kojiadrianojr !

**Comment by harveyjavier** [comment]
Test mic, test

**Comment by swengr-janan** [comment]
Fixed
