### ISSUE TITLE
Selecting [WalletConnect] (Mobile) results to an error.

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#19]
Unhandled Rejection (Error): No RPC Url available for chainId: 97

Video for reference: https://youtu.be/N_H_Hmlko54

**Comment by kojiadrianojr** [comment]
@swengr-janan Please retry this link:  https://0e5882554404.ngrok.io

**Comment by swengr-janan** [comment]
On it!

**Comment by swengr-janan** [comment]
Problem solved using the link you provided @kojiadrianojr

**Comment by swengr-janan** [comment]
Fixed!

**Comment by kojiadrianojr** [comment]
Fix on #20
