### ISSUE TITLE
Layout is cropped in iPad(air/mini) view

### ISSUE THREAD

**Issue by acirrej** [sparkpointio/spark-swap-interface#196]
![image](https://user-images.githubusercontent.com/102147830/172092446-ddcda768-400c-43aa-aee1-eb92cd96fd66.png)
![image](https://user-images.githubusercontent.com/102147830/172092427-59a69368-ca12-413e-ac6d-330ab6722cfc.png)

**Comment by swengr-janan** [comment]
This section was removed.
