### ISSUE TITLE
[Deposit] button is still enabled on different network.

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#23]
I am using Smart Chain - Testnet (BNB) but the [Deposit] button is still enabled in Ethereum networks.

![image](https://user-images.githubusercontent.com/61826995/111264308-36d86380-8662-11eb-88e1-e5dc5c5c8ece.png)

Video for reference: https://youtu.be/W94oaHtdn5c

**Comment by aldrickb** [comment]
Fixed: https://github.com/sparkpointio/sparkdefi-web-app/pull/126

**Comment by swengr-janan** [comment]
> Fixed: [sparkpointio/sparkdefi-web-app#126](https://github.com/sparkpointio/sparkdefi-web-app/pull/126)

Checking Master @aldrickb . Thanks!
