### ISSUE TITLE
Fix sizing of hero image and contents. Please copy whats on mockup

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#239]
<img width="1417" alt="Screen Shot 2022-06-16 at 9 58 34 AM" src="https://user-images.githubusercontent.com/61826995/173974874-42da1b8c-6206-4c92-b5f8-c01f4b20ec34.png">

Mockup:
![image](https://user-images.githubusercontent.com/61826995/173974900-60565d57-d948-458c-9202-225c6816135e.png)

**Comment by justinbalaguer** [comment]
may pr ako kagabi temporary code fix para sa responsiveness. sabay naini @swengr-janan https://github.com/sparkpointio/spark-swap-interface/pull/238 pero yan sa may what's coming up next na garo 2 column dae ko yan nagaya. update ko muna.

**Comment by swengr-janan** [comment]
sige @justinbalaguer , thanksuu!
