### ISSUE TITLE
The scroll behavior sticks to its previous location after clicking a button to another page. 

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#24]
The scroll location retains its previous state after clicking a button going another page.

For more info, please see the video: https://youtu.be/j61SJIg0xTg

**Comment by kojiadrianojr** [comment]
Kuya @swengr-janan If you don't mind po, yung issues po sana sa app.srk.finance sa isang repo nalang po para sorted po. 
Here's the link po: https://github.com/sparkpointio/sparkdefi-web-app
Thank you :)

**Comment by swengr-janan** [comment]
Thanks, Master @kojiadrianojr , I was not aware that there is a separate repo for that. Thank you for the info :)
