### ISSUE TITLE
Send button has no functionality yet

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#240]
Forward emails to _defi@sparkpoint.io_

<img width="734" alt="Screen Shot 2022-06-16 at 10 00 14 AM" src="https://user-images.githubusercontent.com/61826995/173975044-5af9eb54-7b5b-41dd-8937-05a029c2b5b4.png">

**Comment by justinbalaguer** [comment]
anong tig send mo na message tanungin ko sa support kung na receive. meron yan, di ata nalagyan ng message pag nag send na. update ko api na mag send sa defi email akala ko kaya diretso sa support. meron ba at
