### ISSUE TITLE
Fix mobile view display of the following

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#245]
The following displays are taken from iPhone12

- [x] Team page 

![image](https://user-images.githubusercontent.com/61826995/173976908-d1474241-163e-4f1c-a772-54ea25619873.png)

- [x] Online Communities
![image](https://user-images.githubusercontent.com/61826995/173976944-4787b94b-fc69-443d-be03-f24d51cad9f8.png)

- [x] Paving the way ...
![image](https://user-images.githubusercontent.com/61826995/173977031-375fc286-a5bd-4d0e-a9a3-c93519b4b338.png)

- [x] Banner
![image](https://user-images.githubusercontent.com/61826995/173977077-161b33c4-af77-4801-929b-af840f0c0a0f.png)

**Comment by justinbalaguer** [comment]
@swengr-janan
https://github.com/sparkpointio/spark-swap-interface/pull/238
https://github.com/sparkpointio/spark-swap-interface/issues/239#issuecomment-1157148825
