### ISSUE TITLE
Unable to remove liquidity

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#25]
Video for reference: 
https://youtu.be/fOK2sij7_Ic

After I confirm via Meta Mask the transaction, it failed and gives an error.

I took a snapshot of the error:
![image](https://user-images.githubusercontent.com/61826995/111296467-7c5b5780-8687-11eb-9377-f22c8e2dbb56.png)

**Comment by kojiadrianojr** [comment]
I doubled checked po works perfectly fine nung nagremove https://testnet.bscscan.com/tx/0x2ec298877bea09c6c4b7193af62a5c8c654d14f0f92a3cd234dcaf08f49dc033

pero I'll look at this one po

**Comment by swengr-janan** [comment]
Thanks Master @kojiadrianojr

**Comment by swengr-janan** [comment]
Master @kojiadrianojr, tried it again and seems to be working perfectly.  Will close this issue.

Video of re-testing: https://youtu.be/8O8ASyKCv5k
