### ISSUE TITLE
Change to SFUEL/ETH

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#275]
<img width="439" alt="Screen Shot 2022-06-21 at 10 58 43 AM" src="https://user-images.githubusercontent.com/61826995/174707066-899f8baf-7ca1-4e4c-873d-96ca5b19d4f5.png">

**Comment by acirrej** [comment]
![image](https://user-images.githubusercontent.com/102147830/174709856-b31f1255-309e-43ce-a69b-c36a7c7c21e1.png)

Issue fixed thanks @justinbalaguer
