### ISSUE TITLE
Some links redirects to Pancake-related sites.

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#32]
Here is the complete list of the links that redirect to Pancake-related sites.

1. More -> GitHub
2. More -> Docs
3. More -> Blog
4. All links when hovering the Telegram's icon

**Comment by kojiadrianojr** [comment]
on it

**Comment by swengr-janan** [comment]
Fixed

https://github.com/sparkpointio/sparkswap-uikit/pull/5
