### ISSUE TITLE
SparkPoint logo redirects to Pancake's website

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/spark-swap-interface#39]
Video for reference: 

https://user-images.githubusercontent.com/61826995/113124195-d5aab580-9247-11eb-96e1-f4d3a81787a4.mp4

**Comment by kojiadrianojr** [comment]
yes po kasi dyan yung info ng token

**Comment by kojiadrianojr** [comment]
Yes po kasi yung info ng token na nasa page ay from their api :)

**Comment by swengr-janan** [comment]
Ah ok koj. Thanks sa info. Closing this one.
