### ISSUE TITLE
Change language not working

### ISSUE THREAD

**Issue by aldrickb** [sparkpointio/spark-swap-interface#6]
**Bug Description**
Change language not working. Language always in English even if selected another language.
![image](https://user-images.githubusercontent.com/51253561/108799344-0ce3d200-75cb-11eb-879a-d0b1cd722161.png)

**Recommendation**
Hide element or check PancakeSwap repo for bug fixes as PancakeSwap has this error too on their live deployment.

**Comment by kojiadrianojr** [comment]
mas maganda kung ihide muna ata to 

while looking for fix

**Comment by kojiadrianojr** [comment]
suggestion: patch solution for the mean time

**Comment by kojiadrianojr** [comment]
![image](https://user-images.githubusercontent.com/43143132/109140657-c7c0cb00-7797-11eb-99ac-74e1ca7b2002.png)

API problem ata siya

**Comment by aldrickb** [comment]
Yes, hide muna siya before launch. Sarili pa ni pancake yan na API? Na-try mo ng i-discover?

**Comment by kojiadrianojr** [comment]
yung mismong api? havent yet. will check

**Comment by kojiadrianojr** [comment]
sa sparkswap uikit ang fix neto doon natin icontinue @aldrickb

**Comment by kojiadrianojr** [comment]
depreciated na daw ung https://github.com/i18next/i18next-xhr-backend
baka need major major changes para mapagana

**Comment by kojiadrianojr** [comment]
Solved on uikit
